### PR TITLE
PostgreSQL support

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by hubaishan** [comment]
It is important to save `ta_name` in config because `fulltext_postgres_ts_name` can be changed by user from search configuration,  and then the extension will run without indexes  this will affect the speed. 

I recommend making ability to change the `ts_name` because PostgreSQL has ability to add custom dictionaries.

**Comment by VSEphpbb** [comment]
Oh because the index has to be recreated any time it is changed?

**Comment by VSEphpbb** [comment]
@hubaishan When I tried it on postgresql I get really weird and bad results, mainly because the score is super low... like 0.09 (which is less than 0.1, the lowest score we allow). I do not understand with postgresql what range the scores are supposed to be in (it's why I added a `/10` to the query for the sensitivity value. Can you shed any light on that, or tell me if this is behaving like it's supposed to (I don't have a postgresql database with any good content).

**Comment by hubaishan** [comment]
see the commit in code.
reference of `ts_rank_cd` here https://www.postgresql.org/docs/8.3/static/textsearch-controls.html
33 in  `ts_rank_cd` params is 32 +1. 32 also good

**Comment by VSEphpbb** [comment]
@hubaishan The query for getting PG indexes is failing.

```php
$sql = "SELECT c2.relname
FROM pg_catalog.pg_class c1, pg_catalog.pg_index i, pg_catalog.pg_class c2, pg_catalog.pg_get_indexdef(i.indexrelid, 0, true) indexdef
WHERE c1.relname = '" . TOPICS_TABLE . "'
AND position('to_tsvector' in indexdef) > 0
AND pg_catalog.pg_table_is_visible(c1.oid)
AND c1.oid = i.indrelid
AND i.indexrelid = c2.oid;";
```
Gives the error:
> SQL ERROR [ postgres ]<br /><br />ERROR:  function expression in FROM cannot refer to other relations of same query level
LINE 2: ...g_catalog.pg_class c2, pg_catalog.pg_get_indexdef(i.indexrel...

**Comment by VSEphpbb** [comment]
@hubaishan Yeah I saw those docs. They don't help really. It seems that postgresql just sucks at this.

As you can see in the failing test, the board that is created has the following topics:
'Test Topic 1'
'Test Topic 2'
'Test Topic 3'
'Test Framework Topic 4'
'Test Framework Topic 5'

And it can not find any similar topics among those topics. And that's because they are all getting a ranking of 0.

**Comment by hubaishan** [comment]
> @hubaishan The query for getting PG indexes is failing.
It works good in PostgreSQl 9.4.16 on CentOS7 and PostgreSQL 10.3

UPDATE: It is a new feature in 9.3

**Comment by VSEphpbb** [comment]
@hubaishan I worked around it by using phpBB's version of the query for getting indexes, as well as improving the search results by using `to_tsquery()` as you can see from the last 3 commits

**Comment by hubaishan** [comment]
see my commits in code of `driver/postgres.php`

**Comment by VSEphpbb** [comment]
I don't know what you're asking me to look at

**Comment by hubaishan** [comment]
my comments in `driver/postgres.php` for function `get_query()`

**Comment by VSEphpbb** [comment]
I don't see any comments 😢

**Comment by VSEphpbb** [comment]
@hubaishan OK, I've added your updated query codes

**Pull request merged**
