### PR TITLE
Update for FRENCH translation for Precise Similar Topics extension

### PR DESCRIPTION
**Pull request by Galixte**
Update for FRENCH translation for acp_similar_topics.php
Update for FRENCH translation for info_acp_similar_topics.php
Update for FRENCH translation for permissions_similar_topics.php

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Why so many (s) ?? The original English version does not do that.

**Comment by Galixte** [comment]
Hi,

sorry for my late. In French, and for this part :

```
+	'PST_YEARS'			=> 'Année(s)',
 	'PST_MONTHS'		=> 'Mois',
-	'PST_WEEKS'			=> 'Semaines',
-	'PST_DAYS'			=> 'Jours',
+	'PST_WEEKS'			=> 'Semaine(s)',
+	'PST_DAYS'			=> 'Jour(s)',
```

When you select many years, like 2 years in French we say : "2 années", but if you choose 1 year we say : "1 année". I have indicated the "(s)" for situations where the user selected more one year, for example. It the same situation for Months, weeks, etc ...

**Comment by VSEphpbb** [comment]
I get that situation, but you are doing this in a lot of other spots too , like Nombre de sujet(s) similaire(s) à afficher, and this is not something done in any of the other languages or the original english lang. I prefer the translations be truer to the original english version.

**Comment by Galixte** [comment]
OK, i have change this : https://github.com/Galixte/similartopics/commit/e900adb8dd043a10fa88722c33cdf6846a914267

**Comment by Galixte** [comment]
Thanks, update also here : https://www.phpbb.com/customise/db/extension/precise_similar_topics/support/topic/134366?p=396991#p396991

**Pull request merged**
